version: '3.8'

services:
  web:
    build: .
    ports:
      - "8088:8088"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
